
run_1:
	g++ -std=c++17 ./Overload_04_02_02.cpp -o ./build/Overload_04_02_02 -g && ./build/Overload_04_02_02
run_2:
	g++ -std=c++17 ./Overload_04_02_01.cpp -o ./build/Overload_04_02_01 -g && ./build/Overload_04_02_01

