
run_1:
	g++ -std=c++17 ./Constructor_05_02_01.cpp -o ./build/Constructor_05_02_01 -g && ./build/Constructor_05_02_01
run_2:
	g++ -std=c++17 ./Reference_05_01_01.cpp -o ./build/Reference_05_01_01 -g && ./build/Reference_05_01_01
